import assert from 'node:assert/strict';
import {matches,selectShows,setFilters,filtersFor,filterKey,wantsMatrices} from './filter-state.js';
assert.equal(wantsMatrices(),true,'matrix defaults remain available with storage disabled');
globalThis.localStorage={getItem:()=>null};assert.equal(wantsMatrices(),true);
globalThis.localStorage={getItem:()=>'standard'};assert.equal(wantsMatrices(),false);
delete globalThis.localStorage;
const short={id:1,name:'Alpha',genres:['Drama'],rating:8.1,runtime:25,status:'Ended',episodes:6,seasons:1,total_minutes:150,year:2020};
const long={...short,id:2,name:'Beta',episodes:60,seasons:5,total_minutes:1500,rating:9};
const unknown={id:3,name:'Unknown',genres:['Drama'],rating:null,runtime:null};
assert.equal(matches(short,{genres:['Comedy','Drama'],rating:8,length:'short',hours:3,seasons:1}),true);
assert.equal(matches(long,{episodes:20}),false);
assert.equal(matches(unknown,{episodes:20}),false);
assert.equal(matches(unknown,{length:'short'}),false);
setFilters('home',{hours:3,sort:'shortest'});
setFilters('list',{sort:'name'});
assert.deepEqual(selectShows([long,unknown,short],'home'),[short]);
assert.deepEqual(selectShows([long,unknown,short],'list','alpha'),[short]);
assert.deepEqual(filtersFor('home'),{hours:3,sort:'shortest'});
setFilters('home',{});
assert.equal(filterKey('home'),'');
assert.deepEqual(filtersFor('list'),{sort:'name'});
console.log('Page isolation, combined filters, unknown metadata, list search and sorting passed.');
